# Generated by Django 5.2.2 on 2025-06-10 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_job_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='applicant',
            new_name='user',
        ),
    ]
